-- =============================================
-- DATABASE: Insurance
-- =============================================

PERSON (driver-id PK, name, address)
CAR (regno PK, model, year)
ACCIDENT (report-number PK, accd-date, location)
OWNS (driver-id FK, regno FK)
PARTICIPATED (driver-id, regno, report-number FK, damage-amount)


CREATE DATABASE Insurance;
USE Insurance;

CREATE TABLE PERSON (
    driverid VARCHAR(10) PRIMARY KEY,
    name CHAR(15) NOT NULL,
    address VARCHAR(30)
);

INSERT INTO PERSON VALUES ('111', 'John Smith', 'SP Road, Bangalore');
INSERT INTO PERSON VALUES ('112', 'Ramesh Babu', 'KP Nagar, Udupi');
INSERT INTO PERSON VALUES ('113', 'Raju SK', 'KS Circle, Mangalore');
INSERT INTO PERSON VALUES ('114', 'Ramesh Babu', 'AS Road, Bangalore');
INSERT INTO PERSON VALUES ('115', 'Alica Wallace', 'SS Road, Karkala');

CREATE TABLE CAR (
    regno VARCHAR(10) PRIMARY KEY,
    model VARCHAR(10) NOT NULL,
    cyear INT
);

INSERT INTO CAR VALUES ('KA-12', 'FORD', 1980);
INSERT INTO CAR VALUES ('KA-13', 'SWIFT', 1990);
INSERT INTO CAR VALUES ('MH-11', 'INDIGO', 1998);
INSERT INTO CAR VALUES ('AP-10', 'SWIFT', 1988);
INSERT INTO CAR VALUES ('TN-11', 'FORD', 2001);
INSERT INTO CAR VALUES ('TN-12', 'TOYOTA', 2001);
INSERT INTO CAR VALUES ('MH-14', 'SWIFT', 2001);
INSERT INTO CAR VALUES ('KL-15', 'TOYOTA', 2001);
INSERT INTO CAR VALUES ('KL-4', 'INDIGO', 2001);
INSERT INTO CAR VALUES ('AP-05', 'SANTRO', 2001);

CREATE TABLE ACCIDENT (
    reportno INT PRIMARY KEY,
    accdate DATETIME,
    location VARCHAR(20)
);

INSERT INTO ACCIDENT VALUES (1,  '1989-07-22', 'Nitte');
INSERT INTO ACCIDENT VALUES (2,  '1989-07-22', 'Karkala');
INSERT INTO ACCIDENT VALUES (3,  '1989-07-23', 'Mangalore');
INSERT INTO ACCIDENT VALUES (4,  '1989-09-09', 'Bhatkal');
INSERT INTO ACCIDENT VALUES (5,  '1990-02-22', 'Udupi');
INSERT INTO ACCIDENT VALUES (6,  '1990-09-09', 'Udupi');
INSERT INTO ACCIDENT VALUES (7,  '1998-09-09', 'Karkala');
INSERT INTO ACCIDENT VALUES (8,  '1998-09-09', 'Bhatkal');
INSERT INTO ACCIDENT VALUES (9,  '2001-02-22', 'Udupi');
INSERT INTO ACCIDENT VALUES (10, '1998-02-02', 'Udupi');

CREATE TABLE OWNS (
    driverid VARCHAR(10),
    regno    VARCHAR(10),
    PRIMARY KEY (driverid, regno),
    FOREIGN KEY (driverid) REFERENCES PERSON(driverid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (regno)    REFERENCES CAR(regno)       ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO OWNS VALUES ('111', 'KA-12');
INSERT INTO OWNS VALUES ('111', 'KA-13');
INSERT INTO OWNS VALUES ('111', 'MH-11');
INSERT INTO OWNS VALUES ('112', 'AP-10');
INSERT INTO OWNS VALUES ('112', 'TN-11');
INSERT INTO OWNS VALUES ('113', 'TN-12');
INSERT INTO OWNS VALUES ('113', 'KL-15');
INSERT INTO OWNS VALUES ('114', 'AP-05');
INSERT INTO OWNS VALUES ('114', 'KL-4');
INSERT INTO OWNS VALUES ('115', 'MH-14');

CREATE TABLE PARTICIPATED (
    driverid VARCHAR(10),
    regno    VARCHAR(10),
    reportno INT,
    dmgamt   INT,
    PRIMARY KEY (driverid, regno, reportno),
    FOREIGN KEY (driverid) REFERENCES PERSON(driverid)   ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (regno)    REFERENCES CAR(regno)          ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (reportno) REFERENCES ACCIDENT(reportno)  ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PARTICIPATED VALUES ('111', 'KA-12', 1,  20000);
INSERT INTO PARTICIPATED VALUES ('111', 'KA-13', 2,  10000);
INSERT INTO PARTICIPATED VALUES ('111', 'KA-12', 3,  60000);
INSERT INTO PARTICIPATED VALUES ('111', 'KA-12', 4,  60000);
INSERT INTO PARTICIPATED VALUES ('111', 'MH-11', 5,  40000);
INSERT INTO PARTICIPATED VALUES ('112', 'AP-10', 6,  30000);
INSERT INTO PARTICIPATED VALUES ('112', 'TN-11', 7,  40000);
INSERT INTO PARTICIPATED VALUES ('113', 'TN-12', 8,  40000);
INSERT INTO PARTICIPATED VALUES ('113', 'KL-15', 9,  50000);
INSERT INTO PARTICIPATED VALUES ('113', 'TN-12', 10, 20000);
