-- =============================================
-- DATABASE: Order Processing
-- =============================================

CUSTOMER (cust# PK, cname, city)
ORDER (order# PK, odate, cust# FK, ord-Amt)
ORDER-ITEM (order# FK, item# FK, qty)
ITEM (item# PK, unit-price)
SHIPMENT (order# FK, warehouse# FK, ship-date)
WAREHOUSE (warehouse# PK, city)

    2️. Order DB
Table order: CUSTOMER → ITEM → C_ORDER → ORDER_ITEM → WAREHOUSE → SHIPMENT
Values to remember:

Customer IDs: 111 to 115
Order IDs: 201 to 210
Item IDs: 301 to 305, prices: 2000, 2000, 1000, 5000, 4000
Warehouse IDs: 1-6, cities: MANGALORE (1,2,3), UDUPI (4,5), KARKALA (6)
Ship multiple orders from 2+ warehouses — needed for Q2
One customer should have all items ordered — needed for Q3
ordamt — put any non-null values while inserting

CREATE DATABASE ord_proc;
USE ord_proc;

CREATE TABLE CUSTOMER (
    custid INT PRIMARY KEY,
    cname  CHAR(15) NOT NULL,
    city   VARCHAR(30)
);

INSERT INTO CUSTOMER VALUES (111, 'John Smith', 'Karkala');
INSERT INTO CUSTOMER VALUES (112, 'Ramesh N',   'Nitte');
INSERT INTO CUSTOMER VALUES (113, 'Franklin',   'Karkala');
INSERT INTO CUSTOMER VALUES (114, 'Alica',      'Mangalore');
INSERT INTO CUSTOMER VALUES (115, 'Raju',       'Udupi');

CREATE TABLE C_ORDER (
    orderid INT PRIMARY KEY,
    odate   DATETIME,
    custid  INT,
    ordamt  INT,
    FOREIGN KEY (custid) REFERENCES CUSTOMER(custid) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO C_ORDER VALUES (201, '2001-08-03', 111, NULL);
INSERT INTO C_ORDER VALUES (202, '2002-08-03', 111, NULL);
INSERT INTO C_ORDER VALUES (203, '2001-08-04', 112, NULL);
INSERT INTO C_ORDER VALUES (204, '2004-02-01', 113, NULL);
INSERT INTO C_ORDER VALUES (205, '2001-04-02', 114, NULL);
INSERT INTO C_ORDER VALUES (206, '2005-02-01', 115, NULL);
INSERT INTO C_ORDER VALUES (207, '2008-04-01', 115, NULL);
INSERT INTO C_ORDER VALUES (208, '2008-12-01', 111, NULL);
INSERT INTO C_ORDER VALUES (209, '2008-02-01', 114, NULL);
INSERT INTO C_ORDER VALUES (210, '2008-10-01', 111, NULL);

CREATE TABLE ITEM (
    itemid INT PRIMARY KEY,
    price  INT
);

INSERT INTO ITEM VALUES (301, 2000);
INSERT INTO ITEM VALUES (302, 2000);
INSERT INTO ITEM VALUES (303, 1000);
INSERT INTO ITEM VALUES (304, 5000);
INSERT INTO ITEM VALUES (305, 4000);

CREATE TABLE ORDER_ITEM (
    orderid INT,
    itemid  INT,
    qty     INT,
    PRIMARY KEY (orderid, itemid),
    FOREIGN KEY (orderid) REFERENCES C_ORDER(orderid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (itemid)  REFERENCES ITEM(itemid)     ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO ORDER_ITEM VALUES (201, 301, 2);
INSERT INTO ORDER_ITEM VALUES (201, 302, 4);
INSERT INTO ORDER_ITEM VALUES (201, 303, 4);
INSERT INTO ORDER_ITEM VALUES (201, 304, 4);
INSERT INTO ORDER_ITEM VALUES (201, 305, 3);
INSERT INTO ORDER_ITEM VALUES (202, 303, 2);
INSERT INTO ORDER_ITEM VALUES (202, 305, 4);
INSERT INTO ORDER_ITEM VALUES (203, 302, 1);
INSERT INTO ORDER_ITEM VALUES (204, 305, 2);
INSERT INTO ORDER_ITEM VALUES (205, 301, 3);
INSERT INTO ORDER_ITEM VALUES (206, 301, 5);

CREATE TABLE WAREHOUSE (
    warehouseid INT PRIMARY KEY,
    city        VARCHAR(20) NOT NULL
);

INSERT INTO WAREHOUSE VALUES (1, 'MANGALORE');
INSERT INTO WAREHOUSE VALUES (2, 'MANGALORE');
INSERT INTO WAREHOUSE VALUES (3, 'MANGALORE');
INSERT INTO WAREHOUSE VALUES (4, 'UDUPI');
INSERT INTO WAREHOUSE VALUES (5, 'UDUPI');
INSERT INTO WAREHOUSE VALUES (6, 'KARKALA');

CREATE TABLE SHIPMENT (
    orderid     INT,
    warehouseid INT,
    ship_dt     DATETIME,
    PRIMARY KEY (orderid, warehouseid),
    FOREIGN KEY (orderid)     REFERENCES C_ORDER(orderid)     ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (warehouseid) REFERENCES WAREHOUSE(warehouseid) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO SHIPMENT VALUES (201, 1, '2001-04-02');
INSERT INTO SHIPMENT VALUES (201, 2, '2001-04-04');
INSERT INTO SHIPMENT VALUES (202, 1, '2001-05-02');
INSERT INTO SHIPMENT VALUES (202, 2, '2002-05-12');
INSERT INTO SHIPMENT VALUES (202, 3, '2003-06-01');
INSERT INTO SHIPMENT VALUES (202, 4, '2003-06-01');
INSERT INTO SHIPMENT VALUES (203, 1, '2004-02-01');
INSERT INTO SHIPMENT VALUES (203, 2, '2004-02-01');
INSERT INTO SHIPMENT VALUES (203, 3, '2004-02-01');
INSERT INTO SHIPMENT VALUES (204, 4, '2004-06-02');
INSERT INTO SHIPMENT VALUES (204, 2, '2004-06-02');

UPDATE C_ORDER SET ordamt = (
    SELECT SUM(OI.qty * I.price)
    FROM ORDER_ITEM OI, ITEM I
    WHERE OI.itemid = I.itemid
    AND OI.orderid = C_ORDER.orderid
);
-- Q1: customer name, order count, avg amount
SELECT C.cname, COUNT(O.orderid) AS No_Of_Orders, AVG(O.ordamt) AS AVG_ORDER_AMT
FROM CUSTOMER C, C_ORDER O
WHERE C.custid = O.custid GROUP BY C.cname;

-- Q2: items with >2 orders shipped from 2+ warehouses
SELECT OI.itemid, COUNT(DISTINCT OI.orderid) AS Num_Orders, SUM(OI.qty) AS Total_Qty
FROM ORDER_ITEM OI
WHERE OI.orderid IN (
    SELECT S.orderid FROM SHIPMENT S
    GROUP BY S.orderid HAVING COUNT(DISTINCT S.warehouseid) >= 2
)
GROUP BY OI.itemid HAVING COUNT(DISTINCT OI.orderid) > 2;

-- Q3: customers who ordered every item
SELECT C.cname FROM CUSTOMER C
WHERE NOT EXISTS (
    SELECT itemid FROM ITEM
    WHERE itemid NOT IN (
        SELECT OI.itemid FROM C_ORDER O, ORDER_ITEM OI
        WHERE O.orderid = OI.orderid AND O.custid = C.custid
    )
);
